logging:
  level:
    com.example: DEBUG
    org:
      springframework:
        security: DEBUG
  file: log/log.log

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    static-path-pattern: /**
    view:
      prefix: /views/
      suffix: .html
    resources:
      static-locations: classpath:/static/
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true